-- ==============================================================================
-- SKRIP SETUP DATABASE SUPABASE UNTUK APLIKASI PLANNING LEMBUR (PLANBUR)
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. TABEL KARYAWAN
CREATE TABLE IF NOT EXISTS public.karyawan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_karyawan TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL,
    status TEXT DEFAULT 'AKTIF',
    tanggal_lahir TEXT DEFAULT '',
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. TABEL PENALTI
CREATE TABLE IF NOT EXISTS public.penalti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    karyawan_id BIGINT REFERENCES public.karyawan(id) ON DELETE CASCADE,
    alasan TEXT DEFAULT '',
    tanggal TEXT DEFAULT '',
    aktif BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. TABEL PLANNING LEMBUR
CREATE TABLE IF NOT EXISTS public.planning_lembur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_planning TEXT NOT NULL UNIQUE,
    tanggal TEXT NOT NULL,
    jam_mulai TEXT DEFAULT '',
    jam_selesai TEXT DEFAULT '',
    durasi_menit INTEGER DEFAULT 0,
    durasi TEXT DEFAULT '',
    keterangan TEXT DEFAULT '',
    bukti_url TEXT DEFAULT '',
    bukti_nama TEXT DEFAULT '',
    preview_url TEXT DEFAULT '',
    jenis_lembur TEXT DEFAULT 'harian',
    status TEXT DEFAULT 'Planning',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. TABEL PLANNING_KARYAWAN (RELASI)
CREATE TABLE IF NOT EXISTS public.planning_karyawan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_id BIGINT REFERENCES public.planning_lembur(id) ON DELETE CASCADE,
    karyawan_id BIGINT REFERENCES public.karyawan(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) & POLICIES (Agar data bisa dibaca dan disimpan frontend)
-- ==============================================================================

ALTER TABLE public.karyawan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penalti ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planning_lembur ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planning_karyawan ENABLE ROW LEVEL SECURITY;

-- Policy untuk Karyawan
DROP POLICY IF EXISTS "Public access for karyawan" ON public.karyawan;
CREATE POLICY "Public access for karyawan" ON public.karyawan
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policy untuk Penalti
DROP POLICY IF EXISTS "Public access for penalti" ON public.penalti;
CREATE POLICY "Public access for penalti" ON public.penalti
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policy untuk Planning Lembur
DROP POLICY IF EXISTS "Public access for planning_lembur" ON public.planning_lembur;
CREATE POLICY "Public access for planning_lembur" ON public.planning_lembur
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policy untuk Planning Karyawan
DROP POLICY IF EXISTS "Public access for planning_karyawan" ON public.planning_karyawan;
CREATE POLICY "Public access for planning_karyawan" ON public.planning_karyawan
    FOR ALL
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- ==============================================================================
-- STORAGE BUCKET (Untuk foto bukti lembur)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('planning-bukti', 'planning-bukti', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy Storage
DROP POLICY IF EXISTS "Public access to planning-bukti storage" ON storage.objects;
CREATE POLICY "Public access to planning-bukti storage" ON storage.objects
    FOR ALL
    TO anon, authenticated
    USING (bucket_id = 'planning-bukti')
    WITH CHECK (bucket_id = 'planning-bukti');
